<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../NexaFiscal.Inventory.Application/NexaFiscal.Inventory.Application.csproj" />
    <ProjectReference Include="../NexaFiscal.Inventory.Domain/NexaFiscal.Inventory.Domain.csproj" />
  </ItemGroup>
</Project>
