services:
  frontend:
    build:
      context: ./frontend/nexa-fiscal-web
      dockerfile: Dockerfile
    container_name: nexa-fiscal-web
    ports:
      - "4200:80"
    depends_on:
      - inventory-api
      - billing-api
    networks:
      - nexa-network

  inventory-api:
    build:
      context: ./backend/inventory-service
      dockerfile: Dockerfile
    container_name: nexa-inventory-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      FRONTEND_ORIGIN: http://localhost:4200
      Mongo__ConnectionString: mongodb://inventory-db:27017
      Mongo__DatabaseName: NexaFiscalInventory
    ports:
      - "5101:8080"
    depends_on:
      inventory-db:
        condition: service_healthy
    networks:
      - nexa-network

  billing-api:
    build:
      context: ./backend/billing-service
      dockerfile: Dockerfile
    container_name: nexa-billing-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      FRONTEND_ORIGIN: http://localhost:4200
      Mongo__ConnectionString: mongodb://billing-db:27017
      Mongo__DatabaseName: NexaFiscalBilling
      Inventory__BaseUrl: http://inventory-api:8080
    ports:
      - "5102:8080"
    depends_on:
      inventory-api:
        condition: service_started
      billing-db:
        condition: service_healthy
    networks:
      - nexa-network

  inventory-db:
    image: mongo:8.0
    container_name: nexa-inventory-db
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - inventory-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - nexa-network

  billing-db:
    image: mongo:8.0
    container_name: nexa-billing-db
    restart: unless-stopped
    ports:
      - "27019:27017"
    volumes:
      - billing-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - nexa-network

volumes:
  inventory-data:
  billing-data:

networks:
  nexa-network:
    driver: bridge
